#!/usr/bin/env bash
set -euo pipefail

# agentibrain-kernel — K8s bootstrap.
# Idempotent. Safe to re-run.
#
# What it does:
#      EMBEDDINGS_API_KEY) and stores them in local/.k8s-tokens (gitignored).
#   2. Prints (and optionally executes) `kubectl create secret generic` commands
#      for the three Opaque Secrets the kernel charts expect:
#        - embeddings-secrets           (POSTGRES_URL, LLM_API_KEY, LLM_API_BASE, LLM_EMBED_MODEL, EMBEDDINGS_API_KEYS)
#        - agenticore-secrets           (only needed if you deploy brain-keeper)
#
# Usage:
#   ./local/k8s-bootstrap.sh                # print commands only
#   ./local/k8s-bootstrap.sh --apply        # execute kubectl create secret
#   ./local/k8s-bootstrap.sh --apply -n NS  # execute in namespace NS (default: default)
#
# Operators with a real secrets manager (OpenBao / AWS SM / Vault) should
# instead flip externalSecret.enabled in the chart values and skip this script.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TOKENS_FILE="$ROOT/local/.k8s-tokens"
NAMESPACE="default"
APPLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    -n|--namespace) NAMESPACE="$2"; shift 2 ;;
    -h|--help)
      sed -n '4,22p' "$0"
      exit 0
      ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl required to generate tokens" >&2
  exit 1
fi

# 1. Generate / reuse tokens
if [[ -f "$TOKENS_FILE" ]]; then
  echo "[k8s-bootstrap] $TOKENS_FILE exists — reusing tokens"
  # shellcheck disable=SC1090
  source "$TOKENS_FILE"
else
  echo "[k8s-bootstrap] generating fresh tokens → $TOKENS_FILE"
  KB_ROUTER_TOKEN="$(openssl rand -hex 32)"
  EMBEDDINGS_API_KEY="$(openssl rand -hex 32)"
  cat > "$TOKENS_FILE" <<EOF
# Generated by k8s-bootstrap.sh — do not commit.
# These tokens are loaded into the K8s Secrets the kernel charts expect.
KB_ROUTER_TOKEN="${KB_ROUTER_TOKEN}"
EMBEDDINGS_API_KEY="${EMBEDDINGS_API_KEY}"
EOF
  chmod 600 "$TOKENS_FILE"
fi

# 2. Print (or execute) kubectl create commands
ROUTER_CMD="kubectl -n ${NAMESPACE} create secret generic agentibrain-router-secrets \
  --from-literal=KB_ROUTER_TOKEN=\"\$KB_ROUTER_TOKEN\" \
  --from-literal=EMBEDDINGS_API_KEY=\"\$EMBEDDINGS_API_KEY\""

EMBED_CMD="kubectl -n ${NAMESPACE} create secret generic embeddings-secrets \
  --from-literal=POSTGRES_URL=\"\${POSTGRES_URL:?set in env}\" \
  --from-literal=LLM_API_KEY=\"\${LLM_API_KEY:-}\" \
  --from-literal=LLM_API_BASE=\"\${LLM_API_BASE:-}\" \
  --from-literal=LLM_EMBED_MODEL=\"\${LLM_EMBED_MODEL:-text-embedding-3-small}\" \
  --from-literal=EMBEDDINGS_API_KEYS=\"\$EMBEDDINGS_API_KEY\""

KEEPER_CMD="kubectl -n ${NAMESPACE} create secret generic agenticore-secrets \
  --from-literal=ANTHROPIC_API_KEY=\"\${ANTHROPIC_API_KEY:?set in env}\" \
  --from-literal=GITHUB_TOKEN=\"\${GITHUB_TOKEN:-}\""

cat <<EOF

──── Required Secrets (namespace: ${NAMESPACE}) ────

# 1. brain-api + obsidian-reader auth (always required)
${ROUTER_CMD}

# 2. embeddings backend — Postgres + LLM provider (required for brain-api /ingest path)
${EMBED_CMD}

# 3. brain-keeper agent — Claude Anthropic key (only if deploying brain-keeper)
${KEEPER_CMD}

EOF

if [[ "$APPLY" -eq 1 ]]; then
  echo "[k8s-bootstrap] applying secrets in namespace=${NAMESPACE}…"
  source "$TOKENS_FILE"
  exists() { kubectl -n "$NAMESPACE" get secret "$1" >/dev/null 2>&1; }

  if exists agentibrain-router-secrets; then
    echo "  [skip] agentibrain-router-secrets already present"
  else
    eval "${ROUTER_CMD}" && echo "  [ok]   agentibrain-router-secrets"
  fi

  if [[ -z "${POSTGRES_URL:-}" ]]; then
    echo "  [skip] embeddings-secrets — POSTGRES_URL not set in env"
  elif exists embeddings-secrets; then
    echo "  [skip] embeddings-secrets already present"
  else
    eval "${EMBED_CMD}" && echo "  [ok]   embeddings-secrets"
  fi

  if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    echo "  [skip] agenticore-secrets — ANTHROPIC_API_KEY not set in env (skip if not deploying brain-keeper)"
  elif exists agenticore-secrets; then
    echo "  [skip] agenticore-secrets already present"
  else
    eval "${KEEPER_CMD}" && echo "  [ok]   agenticore-secrets"
  fi
else
  echo "[k8s-bootstrap] dry-run — re-run with --apply to execute, or copy/paste the commands above."
fi

cat <<EOF

──── Next steps ────

  helm install brain-api    helm/brain-api    -n ${NAMESPACE}
  helm install obsidian     helm/obsidian-reader -n ${NAMESPACE}
  helm install embeddings   helm/embeddings   -n ${NAMESPACE}
  helm install brain-ops   helm/brain-ops   -n ${NAMESPACE}     # optional
  helm install brain-keeper helm/brain-keeper -n ${NAMESPACE}     # optional

  # smoke
  kubectl -n ${NAMESPACE} port-forward svc/agentibrain-brain-api 8080:8080 &
  source "$TOKENS_FILE"
  curl -fsSL -H "Authorization: Bearer \$KB_ROUTER_TOKEN" http://localhost:8080/feed | jq .

EOF
