apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentibrain-kb-router
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: router=ghcr.io/the-cloud-clock-work/agentibrain-kb-router:dev
    argocd-image-updater.argoproj.io/router.update-strategy: digest
    argocd-image-updater.argoproj.io/router.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/router.helm.image-name: tpl.app.image.repository
    argocd-image-updater.argoproj.io/router.helm.image-tag: tpl.app.image.tag
    argocd-image-updater.argoproj.io/router.pull-secret: secret:argocd/argocd-image-updater-ghcr#credentials
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/router.force-update: "true"
  labels:
    image-updater/image: agentibrain-kb-router
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/The-Cloud-Clock-Work/agentibrain-kernel.git
    targetRevision: v0.1.1
    path: helm/kb-router
  - repoURL: https://github.com/The-Cloud-Clock-Work/agentibrain-kernel.git
    targetRevision: dev
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: anton-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
